In [66]:
import numpy as np
import matplotlib.pyplot as plt

In [90]:
n = 100
Teta = 4
B = 0.95
etta = np.random.uniform(0,1,n)
sample = (1-etta)**(1/(1-Teta))
print(sample)

[2.56400505 1.3796189  1.06366873 1.23606781 1.23465689 1.16095056
 1.53607887 1.07012088 1.07092013 1.1008853  1.33443006 1.07357144
 1.27336194 1.24474214 1.08950639 1.65761639 1.19437391 1.16686846
 1.10197948 1.37760467 1.5514217  1.06595903 1.61447789 1.0734606
 1.01392454 1.20795573 1.67032428 1.07426008 1.33734092 3.2707133
 1.23559923 1.89898283 1.31514347 1.10308775 1.01239416 1.30929443
 2.23526424 2.19770318 1.46987041 1.15466832 1.15790224 1.48689927
 1.20913061 2.35383489 3.328964   1.1306636  2.73581238 1.04619785
 1.54342258 1.11675853 1.45309039 1.67067348 1.062451   1.09524848
 4.76900325 2.78387001 3.48034759 1.69728326 1.04142115 1.3934564
 1.13884958 1.60878706 2.54895413 2.8632117  1.31749061 1.3260854
 1.40773862 1.23350306 1.43384803 1.04588978 1.75391882 1.628145
 1.00651926 1.05217437 1.24557769 1.17573757 1.10129396 1.10920507
 1.22667332 1.70989382 1.05652545 1.36274412 1.39881859 1.30797964
 1.00985419 3.129981   1.02832748 1.02761668 1.1618791  1.03925289
 

In [91]:
S = 0
for i in sample:
  S += np.log(i)
Teta = (n/S)+1
print(Teta)

3.858837446234064


In [106]:
a = -1.96*(((2**(1/(Teta-1)))*np.log(2))/((Teta-1)*(n**(1/2))))+2**(1/(Teta-1))
b = 1.96*(((2**(1/(Teta-1)))*np.log(2))/((Teta-1)*(n**(1/2))))+2**(1/(Teta-1))
L_confidence_interval_for_mediana = b-a
print(f"confidence_interval_for_mediana ({a},{b})")

confidence_interval_for_mediana (1.2028647492953064,1.31697735049444)


In [107]:
a = -1.96*((Teta-1)/(n**(1/2)))+Teta
b = 1.96*((Teta-1)/(n**(1/2)))+Teta
L_confidence_interval_for_param = b-a
print(f"confidence_interval_for_param ({a},{b})")


confidence_interval_for_param (3.412,4.588)


In [108]:
N = 10000
Teta = 4
all_samples = []
all_tetas = []
for _ in range(N):
  etta = np.random.uniform(0,1,n)
  sample_ = (1-etta)**(1/(1-Teta))
  all_samples.append(sample_)
  S = 0
  for i in sample_:
    S += np.log(i)
    teta_ = (n/S)+1
  all_tetas.append(teta_)
all_samples = np.array(all_samples)
all_tetas = np.array(all_tetas)
print(all_samples)
print(all_samples.shape)


[[1.12946855 1.12690528 1.14164189 ... 1.07828943 2.10467302 1.22228372]
 [1.14048677 1.00958929 1.19773887 ... 1.0104132  1.84907224 1.96755535]
 [1.07602499 1.61499067 1.73383599 ... 1.38820123 1.09406972 1.09857074]
 ...
 [1.03503851 1.69998365 1.12111363 ... 1.01252242 1.14379064 1.12307554]
 [1.04952247 1.01146376 1.15988616 ... 5.15772632 1.0052478  1.09860471]
 [1.45786284 1.05469219 1.72464997 ... 1.4486886  1.12484726 3.21345795]]
(10000, 100)


In [109]:
print(all_tetas)
print(all_tetas.shape)

[3.70262231 3.55037174 3.9828727  ... 4.59260163 3.9597637  3.94281083]
(10000,)


In [110]:
all_tetas.sort()
all_tetas

array([3.06897197, 3.09009133, 3.11639193, ..., 5.37897687, 5.44071871,
       5.5536225 ])

In [111]:
K1 = int(N*(1-B)/2)
K2 = int(N*(1+B)/2)
parametric_bootstrap_interval = (all_tetas[K1], all_tetas[K2])
L_parametric_bootstrap_interval = all_tetas[K2]-all_tetas[K1]
parametric_bootstrap_interval

(3.480878896132415, 4.704638632679297)

In [114]:
L_min_interval = min(L_confidence_interval_for_mediana, L_confidence_interval_for_param, L_parametric_bootstrap_interval)
L_max_interval = max(L_confidence_interval_for_mediana, L_confidence_interval_for_param, L_parametric_bootstrap_interval)
print(f"Длина доверительного интервала для медианы: {L_confidence_interval_for_mediana},\n Длина доверительного интервала для параметра: {L_confidence_interval_for_param},\n "
f"Длина бутстраповского доверительного интервала: {L_parametric_bootstrap_interval},\n Макс. длина интервала: {L_max_interval},\n Мин. длина интервала: {L_min_interval}.\n")

Длина доверительного интервала для медианы: 0.11411260119913358,
 Длина доверительного интервала для параметра: 1.1760000000000002,
 Длина бутстраповского доверительного интервала: 1.2237597365468815,
 Макс. длина интервала: 1.2237597365468815,
 Мин. длина интервала: 0.11411260119913358.



0.6931471805599453